"""
Django settings for Qshop project.

Generated by 'django-admin startproject' using Django 2.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'q755cer4tyiji4xwaq&6ji4uq@gqwqayhh0q8yo4ay)1$6%_j2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'QUser',
    'Shop',
    'djcelery',
    'ckeditor',
    'ckeditor_uploader',
    'Buyer'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Qshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Qshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/' #死得第科_油啊安奥
STATICFILES_DIRS =[  #死得第科非奥斯_第哎儿斯
    os.path.join(BASE_DIR, "static")
]

MEDIA_URL = '/media/'#米的藕 url
MEDIA_ROOT = os.path.join(BASE_DIR,"static")

# STATIC_ROOT = os.path.join(BASE_DIR, "static")
MAIL_SENDER = "2719929303@qq.com"#自己的qq号
MATL_PASSWORD = "bveikvhxwpeodgji"
MAIL_SERVER = "smtp.qq.com"
MAIL_PORT = 465

# celery框架异步任务配置
import djcelery

djcelery.setup_loader()#初始化celery异步任务

BROKER_URL = "redis://127.0.0.1:6379/1"
CELERY_IMPORTS = ('CeleryTask.tasks')#具体存放celery任务的地方
CELERY_TIMEZONE = 'Asia/Shanghai'#celery定时任务使用的时区
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'#celery的处理器

from celery.schedules import timedelta

CELERYBEAT_SCHEDULE = {
    u"测试任务1":{
        "task":"Celery.tasks.add",
        "schedule":timedelta(seconds=1)
    },
    u"测试任务2":{
        "task":"Celery.tasks.add",
        "schedule":timedelta(seconds=1)
    } #用来给计划任务传递参数的
}

CKEDITOR_UPLOAD_PATH = "upload"
CKEDITOR_IMAGE_BACKEND = "pillow"

PAZE_SIZE = 5