# Generated by Django 2.1.8 on 2019-10-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_auto_20191031_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsTypeManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
