# Generated by Django 2.1.8 on 2019-10-31 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QUser', '0002_auto_20191029_0905'),
        ('Shop', '0005_quser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoodsTypeManager',
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='QUser.Quser'),
            preserve_default=False,
        ),
    ]
