# Generated by Django 2.1.8 on 2019-10-31 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_auto_20191031_1633'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quser',
        ),
    ]
