# Generated by Django 2.1.8 on 2019-11-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_delete_quser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='production',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
