# Generated by Django 2.1.8 on 2019-10-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quser',
            name='picture',
            field=models.ImageField(default='image/2.jpeg', upload_to='image'),
        ),
    ]
